spring.application.name=Rent_It
server.port=8086

spring.datasource.url=jdbc:postgresql://db.vtmdkidojukhewbdrtab.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=DhanrajSapkale@22

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

property.image.path=uploads
app.base-url=http://localhost:8086




spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a710c3001@smtp-brevo.com
spring.mail.password=bskOZyWcwFubGJu

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true 

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:114863103184-hbaqr0ds1r1tpvos1d8vj7f6itqil132.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}
spring.security.oauth2.client.registration.google.scope=email,profile,openid
